version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2004:current
    parameters:
      stack:
        type: "string"
    steps:
      - checkout
      - run: bash support/test.sh << parameters.stack >>

workflows:
  version: 2
  all-tests:
    jobs:
      - test:
          name: Heroku-18 Test
          stack: heroku-18
      - test:
          name: Heroku-20 Test
          stack: heroku-20
      - test:
          name: Heroku-22 Test
          stack: heroku-22
