version: 2.1

jobs:
  test:
    parameters:
      stack:
        type: "string"
    steps:
      - run: ./support/test.sh << parameters.stack >>

workflows:
  version: 2
  all-tests:
    jobs:
      - test:
        stack: "cedar-14"
      - test:
        stack: "heroku-16"
      - test:
        stack: "heroku-18"
      - test:
        stack: "heroku-20"
